name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verificar se index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "index.html não encontrado! Falhando o workflow."
            exit 1
          fi

  deploy:
    needs: check-index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
